---
# Whether to upgrade homebrew and all packages installed by homebrew.
# If you prefer to manually update packages via brew commands, leave this set to false.
homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  - atuin
  - autoconf
  - bash-completion
  - bat
  - btop
  - chezmoi
  - cowsay
  - diff-so-fancy
  - doxygen
  - fastfetch
  - fish
  - fortune
  - gettext
  - gh
  - gifsicle
  - go
  - gum
  - httpie
  - iperf
  - jello
  - lazygit
  - libevent
  - lsd
  - neovim
  - nmap
  - node
  - nvm
  - openssl
  - php
  - pngpaste
  - pv
  - python-packaging
  - readline
  - sqlite
  - starship
  - wget
  - wrk
  - zsh-history-substring-search
  - texlab

homebrew_taps: ["domt4/autoupdate"]

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - adobe-creative-cloud
  - adobe-dng-converter
  - airfoil
  - alcove
  - alfred
  - ammonite
  - audio-hijack
  - autodesk-fusion
  - bbedit
  - betterdisplay
  - discord
  - elgato-capture-device-utility
  - elgato-stream-deck
  - fission
  - font-jetbrains-mono-nerd-font
  - font-sf-mono-nerd-font-ligaturized
  - font-zed-mono
  - font-zed-mono-nerd-font
  - font-zed-sans
  - ghostty
  - gpg-suite
  - hazel
  - hex-fiend
  - iterm2
  - itermai
  - kaleidoscope
  - keyboard-maestro
  - latest
  - linearmouse
  - little-snitch
  - mactex
  - netnewswire
  - obs
  - obsidian
  - setapp
  - skim
  - slack
  - soundsource
  - steam
  - syncthing-app
  - texstudio
  - tower
  - vuescan
  - winbox
  - zed
  - zoom
